### PR TITLE
Change to a package actually updated in the last 5 years

### PR DESCRIPTION
**Pull request by kokarn**
Tried a PR 2 weeks ago, didn't get any traction.
Created a new repo and rewrote with proper tests and updated versions.

### CODE REVIEW

**Comment by tbrand** [comment]
Good catch! I would like you to join to this repo as a collaborator. Would you?

**Comment by kokarn** [comment]
Oh very cool! Thanks!

**Comment by tbrand** [comment]
Please merge by yourself if CI would be passed. 👍 Thanks. 😄

**Comment by tbrand** [comment]
I've sent the invitation. 😄

**Comment by kokarn** [comment]
And I've accepted! Will fix the CI issues... Should've tested better before submitting the PR :D

**Comment by tbrand** [comment]
Not necessary. Please try on this PR.

**Comment by kokarn** [comment]
So I ended up rewriting most of the whole package... 

This should be faster and more resilient but should absolutely be a 2.0 version as some behaviours have changed.
Would you mind have a look at the code and make sure I didn't miss anything obvious?

Changes:
* No longer tries to parse `embedded.mobileprovision` if there is none
* Runs all tasks in parallel
* Handles error more cleanly
* Doesn't crash if trying to read entitlements from an un-signed package

Also updated all dependencies and added some `^` to the ranges for future-proofing

**Comment by tbrand** [comment]
Cool! Let me merge this. :+1:

**Pull request merged**
